"""Create initial tables for implementations, scp_profiles, and atoms

Revision ID: 6731ca9150cc
Revises: 
Create Date: 2025-08-14 12:03:38.271141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6731ca9150cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atom_id', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atoms_atom_id'), 'atoms', ['atom_id'], unique=True)
    op.create_index(op.f('ix_atoms_id'), 'atoms', ['id'], unique=False)
    op.create_table('implementations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('subsidiary_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementations_id'), 'implementations', ['id'], unique=False)
    op.create_index(op.f('ix_implementations_owner_user_id'), 'implementations', ['owner_user_id'], unique=True)
    op.create_table('scp_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implementation_id', sa.Integer(), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['implementation_id'], ['implementations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scp_profiles_id'), 'scp_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scp_profiles_id'), table_name='scp_profiles')
    op.drop_table('scp_profiles')
    op.drop_index(op.f('ix_implementations_owner_user_id'), table_name='implementations')
    op.drop_index(op.f('ix_implementations_id'), table_name='implementations')
    op.drop_table('implementations')
    op.drop_index(op.f('ix_atoms_id'), table_name='atoms')
    op.drop_index(op.f('ix_atoms_atom_id'), table_name='atoms')
    op.drop_table('atoms')
    # ### end Alembic commands ###
